### ISSUE TITLE
Not rendering expanded input when match fails

### ISSUE THREAD

**Issue by pdubroy** [cdglabs/ohm-editor#4]
When the match fails, we're not rendering any input:

![screen shot 2016-11-18 at 5 11 11 pm](https://cloud.githubusercontent.com/assets/17293/20436874/13fc21b8-adb2-11e6-81ad-9f3642c4e4a6.png)

We used to render it in grey, like this:

![screen shot 2016-11-18 at 5 15 42 pm](https://cloud.githubusercontent.com/assets/17293/20436998/a947501c-adb2-11e6-93c4-cd021f1a9562.png)

(This is an image from the version https://github.com/cdglabs/ohm/commit/decc045ae59c4a5a5b32c4e3d9c19bbefd389470)

**Comment by pdubroy** [comment]
@lilyx, if you have a chance, could you look at this too?

**Comment by pdubroy** [comment]
It might be due to the recent incremental changes.

**Comment by lilyx** [comment]
Solved by the latest commit: https://github.com/cdglabs/ohm-editor/commit/13f20b89303c3abb2286befe1e51d12362dc1a20

**Comment by pdubroy** [comment]
Great, thanks! Let's close the issue then.
